{"cveId": "CVE-2014-3429", "cwe": ["CWE-94", "CWE-94"], "cvss": [{"baseScore": "6.8", "version": "2.0", "Attack Vector": "None", "Attack Complexity": "M", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "Partial", "Integrity Impact": "P", "Availability Impact": "P"}], "references": ["http://lists.opensuse.org/opensuse-updates/2014-08/msg00039.html", "https://exchange.xforce.ibmcloud.com/vulnerabilities/94497", "https://github.com/ipython/ipython/pull/4845", "https://bugzilla.redhat.com/show_bug.cgi?id=1119890", "http://advisories.mageia.org/MGASA-2014-0320.html", "http://lambdaops.com/cross-origin-websocket-hijacking-of-ipython", "http://seclists.org/oss-sec/2014/q3/152", "http://permalink.gmane.org/gmane.comp.python.ipython.devel/13198", "http://www.mandriva.com/security/advisories?name=MDVSA-2015:160"], "description": ["IPython Notebook 0.12 through 1.x before 1.2 does not validate the origin of websocket requests, which allows remote attackers to execute arbitrary code by leveraging knowledge of the kernel id and a crafted page."], "published": "2014-08-07T11:13:34.843", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}