{"cveId": "CVE-2020-29128", "cwe": ["CWE-91", "CWE-91"], "cvss": [{"baseScore": "9.8", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://github.com/petl-developers/petl/pull/527", "https://petl.readthedocs.io/en/stable/changes.html", "https://github.com/petl-developers/petl/issues/526", "https://github.com/petl-developers/petl/compare/v1.6.7...v1.6.8", "https://github.com/petl-developers/petl/pull/527/commits/1b0a09f08c3cdfe2e69647bd02f97c1367a5b5f8", "https://github.com/petl-developers/petl/security/advisories/GHSA-f5gc-p5m3-v347", "https://github.com/nvn1729/advisories/blob/master/cve-2020-29128.md"], "description": ["petl before 1.68, in some configurations, allows resolution of entities in an XML document."], "published": "2020-11-26T05:15:10.470", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": ["https://github.com/petl-developers/petl/security/advisories/GHSA-f5gc-p5m3-v347"], "commits": [], "pocAdvisorie": {}, "repo": "https://github.com/petl-developers/petl/", "info": {"exist": true, "topics": [], "langs": {"Python": 1056161, "Jupyter Notebook": 21938, "Shell": 2605}, "avatar": "https://avatars.githubusercontent.com/u/41684996?v=4", "stargazers": 1263, "language": "Python"}}, "pocList": []}