{"cveId": "CVE-2022-48860", "cwe": ["CWE-401", "CWE-401"], "cvss": [{"baseScore": "5.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://git.kernel.org/stable/c/669172ce976608b25a2f76f3c65d47f042d125c9", "https://git.kernel.org/stable/c/b7220f8e9d6c6b9594ddfb3125dad938cd478b1f", "https://git.kernel.org/stable/c/8609e29611befc4bfbe7a91bb50fc65ae72ff549", "https://git.kernel.org/stable/c/8ee065a7a9b6a3976c16340503677efc4d8351f6", "https://git.kernel.org/stable/c/979b418b96e35f07136f77962ccfaa54cf3e30e1", "https://git.kernel.org/stable/c/5e7c402892e189a7bc152b125e72261154aa585d", "https://git.kernel.org/stable/c/1852854ee349881efb78ccdbbb237838975902e4", "https://git.kernel.org/stable/c/b19ab4b38b06aae12442b2de95ccf58b5dc53584"], "description": ["In the Linux kernel, the following vulnerability has been resolved:\n\nethernet: Fix error handling in xemaclite_of_probe\n\nThis node pointer is returned by of_parse_phandle() with refcount\nincremented in this function. Calling of_node_put() to avoid the\nrefcount leak. As the remove function do."], "published": "2024-07-16T13:15:12.940", "state": "PUBLIC", "vendorName": ["Linux"], "productName": ["Linux"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}