{"cveId": "CVE-2018-14650", "cwe": ["CWE-732", "CWE-732", "CWE-276", "CWE-732", "CWE-276"], "cvss": [{"baseScore": "1.9", "version": "2.0", "Attack Vector": "Low", "Attack Complexity": "M", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "Partial", "Integrity Impact": "None", "Availability Impact": "None"}], "references": ["https://access.redhat.com/errata/RHSA-2018:3663", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14650", "https://github.com/sosreport/sos-collector/commit/72058f9253e7ed8c7243e2ff76a16d97b03d65ed"], "description": ["It was discovered that sos-collector does not properly set the default permissions of newly created files, making all files created by the tool readable by any local user. A local attacker may use this flaw by waiting for a legit user to run sos-collector and steal the collected data in the /var/tmp directory."], "published": "2018-09-27T20:29:00.260", "state": "PUBLIC", "vendorName": ["[UNKNOWN]"], "productName": ["sos-collector"], "github": {"advisories": [], "commits": ["https://github.com/sosreport/sos-collector/commit/72058f9253e7ed8c7243e2ff76a16d97b03d65ed"], "pocAdvisorie": null, "repo": "https://github.com/sosreport/sos-collector/", "info": {"exist": true, "topics": [], "langs": {"Python": 125304}, "avatar": "https://avatars.githubusercontent.com/u/908256?v=4", "stargazers": 15, "language": "Python"}}, "pocList": []}