{"cveId": "CVE-2018-16880", "cwe": ["CWE-787", "CWE-787", "CWE-787", "CWE-787", "CWE-787"], "cvss": [{"baseScore": "7.0", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "High", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00037.html", "http://www.securityfocus.com/bid/106735", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880", "https://support.f5.com/csp/article/K03593314", "https://usn.ubuntu.com/3903-1/", "https://usn.ubuntu.com/3903-2/"], "description": ["A flaw was found in the Linux kernel's handle_rx() function in the [vhost_net] driver. A malicious virtual guest, under specific conditions, can trigger an out-of-bounds write in a kmalloc-8 slab on a virtual host which may lead to a kernel memory corruption and a system panic. Due to the nature of the flaw, privilege escalation cannot be fully ruled out. Versions from v4.16 and newer are vulnerable."], "published": "2019-01-29T16:29:00.387", "state": "PUBLIC", "vendorName": ["The Linux Foundation"], "productName": ["kernel"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}