{"cveId": "CVE-2018-1092", "cwe": ["CWE-476", "CWE-476"], "cvss": [{"baseScore": "7.1", "version": "2.0", "Attack Vector": "None", "Attack Complexity": "M", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "Complete"}], "references": ["https://usn.ubuntu.com/3754-1/", "https://access.redhat.com/errata/RHSA-2018:2948", "https://access.redhat.com/errata/RHSA-2018:3083", "https://access.redhat.com/errata/RHSA-2018:3096", "http://openwall.com/lists/oss-security/2018/03/29/1", "https://usn.ubuntu.com/3676-1/", "https://usn.ubuntu.com/3676-2/", "https://www.debian.org/security/2018/dsa-4188", "https://bugzilla.kernel.org/show_bug.cgi?id=199179", "https://bugzilla.kernel.org/show_bug.cgi?id=199275", "https://git.kernel.org/pub/scm/linux/kernel/git/tytso/ext4.git/commit/?id=8e4b5eae5decd9dfe5a4ee369c22028f90ab4c44", "https://lists.debian.org/debian-lts-announce/2018/05/msg00000.html", "https://usn.ubuntu.com/3677-1/", "https://usn.ubuntu.com/3677-2/", "https://usn.ubuntu.com/3678-1/", "https://usn.ubuntu.com/3678-2/", "https://usn.ubuntu.com/3678-3/", "https://usn.ubuntu.com/3678-4/", "https://www.debian.org/security/2018/dsa-4187", "https://bugzilla.redhat.com/show_bug.cgi?id=1560777"], "description": ["The ext4_iget function in fs/ext4/inode.c in the Linux kernel through 4.15.15 mishandles the case of a root directory with a zero i_links_count, which allows attackers to cause a denial of service (ext4_process_freed_data NULL pointer dereference and OOPS) via a crafted ext4 image."], "published": "2018-04-02T03:29:00.230", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["Linux kernel through version 4.15"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}