{"cveId": "CVE-2024-8019", "cwe": ["CWE-434", "CWE-434", "CWE-434"], "cvss": [{"baseScore": "9.1", "version": "3.0", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://huntr.com/bounties/2754298b-5af5-48ef-8b38-999093ddf2bd", "https://github.com/lightning-ai/pytorch-lightning/commit/330af381de88cff17515418a341cbc1f9f127f9a"], "description": ["In lightning-ai/pytorch-lightning version 2.3.2, a vulnerability exists in the `LightningApp` when running on a Windows host. The vulnerability occurs at the `/api/v1/upload_file/` endpoint, allowing an attacker to write or overwrite arbitrary files by providing a crafted filename. This can lead to potential remote code execution (RCE) by overwriting critical files or placing malicious files in sensitive locations."], "published": "2025-03-20T10:15:39.010", "state": "PUBLIC", "vendorName": ["lightning-ai"], "productName": ["lightning-ai/pytorch-lightning"], "github": {"advisories": [], "commits": ["https://github.com/lightning-ai/pytorch-lightning/commit/330af381de88cff17515418a341cbc1f9f127f9a"], "pocAdvisorie": null, "repo": "https://github.com/lightning-ai/pytorch-lightning/", "info": {"exist": true, "topics": ["ai", "artificial-intelligence", "data-science", "deep-learning", "machine-learning", "python", "pytorch"], "langs": {"Python": 4745269, "Shell": 10985, "Dockerfile": 10759, "Makefile": 1822}, "avatar": "https://avatars.githubusercontent.com/u/58386951?v=4", "stargazers": 29246, "language": "Python"}}, "pocList": []}